### ISSUE TITLE
不兼容 nodejs 5.x , 6.x

### ISSUE THREAD

**Issue by sandwich99** [XadillaX/aliyun-ons#10]
运行环境 Ubuntu 14.04

在nodejs 5.x 下运行结果
```
Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/data/projects/pusher/node_modules/ons/lib/consumer.js:16:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

6.x 下

```
Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/projects/pusher/node_modules/ons/lib/consumer.js:16:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

**Comment by XadillaX** [comment]
切环境之后需要重新安装依赖——不同版本下安装的 C++ Native 包无法兼容。

> 这也是一个为什么不要把 node_modules 放到版本库中的一个重要原因，因为换了版本就要重新安装编译一遍依赖。以及在不同系统下安装好的依赖也不应复制到别的系统用。

**Comment by sandwich99** [comment]
每次切换都是执行了 npm rm ons 再执行代码的.

我的默认环境是 6.x ,  1.5.0 不能正常运行, 我才逐步降级到 4.x 的

所以不存在切换版本之后没有重新安装依赖的问题

**Comment by XadillaX** [comment]
我在本地无法复现啊，都能正常安装和使用的。

**Comment by sandwich99** [comment]
我使用的 n 作 nodejs 版本管理
系统是 Ubuntu 14.04

之前 1.4 都能正常安装的

算了,  折腾环境就复杂了, 等我有时间再详细找找原因, 保持 close 吧

**Comment by sandwich99** [comment]
![image](https://cloud.githubusercontent.com/assets/1179783/16861501/d62fcdcc-4a73-11e6-98e6-9df8284fbdc2.png)
操作流程
