### ISSUE TITLE
Object.exports.restoreStdout (/home/vagrant/server/web/node_modules/.npminstall/ons/2.3.1/ons/lib/_stdout.js:35:13)

### ISSUE THREAD

**Issue by XadillaX** [XadillaX/aliyun-ons#18]
```sh
throw new TypeError('invalid data');
    ^

TypeError: invalid data
    at WriteStream.Socket.write (net.js:641:11)
    at /home/vagrant/server/web/node_modules/.npminstall/ons/2.3.1/ons/lib/_stdout.js:36:34
    at Array.forEach (native)
    at Object.exports.restoreStdout (/home/vagrant/server/web/node_modules/.npminstall/ons/2.3.1/ons/lib/_stdout.js:35:13)
    at /home/vagrant/server/web/node_modules/.npminstall/ons/2.3.1/ons/lib/consumer.js:91:33
```

Issue found by @mapleincode.

**Comment by XadillaX** [comment]
@mapleincode can you recurrence it?
