### ISSUE TITLE
Error: Error relocating /app/node_modules/ons/build/Release/ons.node: backtrace_symbols: symbol not found

### ISSUE THREAD

**Issue by miserylee** [XadillaX/aliyun-ons#23]
```bash
/app # node .
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Error relocating /app/node_modules/ons/build/Release/ons.node: backtrace_symbols: symbol not found
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/ons/lib/logger.js:17:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
/app # 
```

**Comment by XadillaX** [comment]
What OS / CPU do you use? and how your code looks like?

**Comment by miserylee** [comment]
开发机 macOS Sierra CPU Intel Core i5
运行环境是 Docker  alpine linux 镜像

**Comment by XadillaX** [comment]
阿里云提供的 C++ 静态链接库目测不支持 Alpine Linux。

**Comment by XadillaX** [comment]
你可以换个常用点的 Linux 发行版，如 Ubuntu 或者 CentOS 等。

**Comment by XadillaX** [comment]
或者推荐你去阿里云提工单，让他们把链接库升级成支持 Alpine。那边完成之后我这边做相应升级改造即可。

**Comment by miserylee** [comment]
thx，暂时先使用Rest API方式来处理了。
