### ISSUE TITLE
在ubuntu14.04下编译失败，node版本4.3.2

### ISSUE THREAD

**Issue by 991glasses** [XadillaX/aliyun-ons#6]
```
root@iZ944lt6gklZ:/tmp/tmp# npm i ons

ons@1.3.0 install /tmp/tmp/node_modules/ons
node-gyp rebuild

make: Entering directory `/tmp/tmp/node_modules/ons/build'
  CXX(target) Release/obj.target/ons/src/entry.o
  CXX(target) Release/obj.target/ons/src/consumer_ack.o
  CXX(target) Release/obj.target/ons/src/consumer.o
../src/consumer.cpp: In static member function ‘static void ONSConsumerV8::HandleMessage(uv_async_t*)’:
../src/consumer.cpp:261:92: error: no matching function for call to ‘SetMethod(v8::Local<v8::ObjectTemplate>&, const char [5], void (&)(const Nan::FunctionCallbackInfo<v8::Value>&))’
     Nan::SetMethod<v8::Local<v8::ObjectTemplate>>(ack_templ, "done", ONSConsumerACKV8::Done);
                                                                                            ^
../src/consumer.cpp:261:92: note: candidate is:
In file included from ../src/consumer.h:20:0,
                 from ../src/consumer.cpp:18:
../node_modules/nan/nan.h:1884:17: note: template<class T, template<class> class HandleType> void Nan::SetMethod(HandleType<T>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1884:17: note:   template argument deduction/substitution failed:
../src/consumer.cpp:261:92: note:   deduced conflicting types for parameter ‘T’ (‘v8::Local<v8::ObjectTemplate>’ and ‘v8::ObjectTemplate’)
     Nan::SetMethod<v8::Local<v8::ObjectTemplate>>(ack_templ, "done", ONSConsumerACKV8::Done);
                                                                                            ^
make: *** [Release/obj.target/ons/src/consumer.o] Error 1
make: Leaving directory `/tmp/tmp/node_modules/ons/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/tmp/node_modules/ons
gyp ERR! node -v v4.3.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "ons"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! ons@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ons@1.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ons package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ons
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/tmp/npm-debug.log
```

**Comment by XadillaX** [comment]
已在 `1.3.1` 中修复，请升级。

变动请参照此处 [Compare](https://github.com/XadillaX/aliyun-ons/compare/14369af0b3fdf7d525cdcf6652c3806418a1a21e...4cb84b0f16591133f9071693715e392a7a0852d8)。
